### ISSUE TITLE
Help to port this theme to helix

### ISSUE THREAD

**Issue by zoedsoupe** [soft-aesthetic/soft-era-vim#13]
I'm trying to port this theme to helix but i'm having some trouble. Could you help me to define this theme correctly following the [helix docs](https://docs.helix-editor.com/themes.html)?

<img width="878" alt="image" src="https://github.com/soft-aesthetic/soft-era-vim/assets/44469426/c350d2fe-8af6-4254-b762-eb5c224687ef">

that's my source code for now:
```toml
# soft-era.toml

# Core UI elements
"ui.background"                   = { bg = "#f9f5f5" }
"ui.cursor"                       = { fg = "#ede1ca", bg = "#4a4543" }
"ui.cursorline"                   = { bg = "#fdfbfb" }
"ui.cursorcolumn"                 = { bg = "#fdfbfb" }
"ui.selection"                    = { bg = "#cfc9f466" }
"ui.linenr"                       = { fg = "#e7d8d8cc" }
"ui.directory"                    = { fg = "#87b6b6" }
"ui.diff.add"                     = { fg = "#ffffff", bg = "#98c4ba" }
"ui.diff.change"                  = { fg = "#ffffff", bg = "#cabf9a" }
"ui.diff.delete"                  = { fg = "#ffffff", bg = "#dd698c" }
"ui.diff.text"                    = { modifiers = ["reverse"] }
"ui.error"                        = { fg = "#dd698c", bg = "#f9f5f5" }
"ui.folded"                       = { fg = "#d9c8c8" }
"ui.foldcolumn"                   = { fg = "#958ac5", bg = "#eceafa" }
"ui.signcolumn"                   = { fg = "#958ac5", bg = "#eceafa" }
"ui.incsearch"                    = { fg = "#948484", bg = "#fff7cc", modifiers = ["underline"] }
"ui.match_paren"                  = { bg = "#4a4543" }
"ui.mode_message"                 = { fg = "#c29ba3", bg = "#e9e4e1" }
"ui.normal"                       = { fg = "#c29ba3", bg = "#f9f5f5" }
"ui.pmenu"                        = { fg = "#d9c8c8", bg = "#cabf9a" }
"ui.pmenu.sel"                    = { fg = "#fdfbfb", bg = "#958ac5" }
"ui.question"                     = { fg = "#4a4543" }
"ui.search"                       = { fg = "#948484", bg = "#fffce9", modifiers = ["underline"] }
"ui.spell_bad"                    = { fg = "#dd698c", modifiers = ["undercurl"] }
"ui.spell_local"                  = { fg = "#dd698c", modifiers = ["undercurl"] }
"ui.spell_cap"                    = { fg = "#c9afe0", modifiers = ["undercurl"] }
"ui.spell_rare"                   = { fg = "#fff7cc", modifiers = ["undercurl"] }
"ui.statusline"                   = { fg = "#d9c8c8", bg = "#e9e4e1" }
"ui.statusline.inactive"          = { fg = "#d9c8c8", bg = "#f2edec" }
"ui.tabline"                      = { fg = "#c29ba3", bg = "#e9e4e1" }
"ui.tabline.fill"                 = { fg = "#d6d5d4", bg = "#e9e4e1" }
"ui.tabline.sel"                  = { fg = "#4a4543", bg = "#f9f5f5" }
"ui.title"                        = { fg = "#958ac5", modifiers = ["bold"] }
"ui.visual"                       = { fg = "#958ac5", bg = "#d6d5d4" }
"ui.warning_msg"                  = { fg = "#e4846f" }

# Syntax highlighting
"attribute"                       = { fg = "#87b6b6", modifiers = ["italic"] }
"comment"                         = { fg = "#d9c8c8", modifiers = ["italic"] }
"constant"                        = { fg = "#d9ade8" }
"constant.character"              = { fg = "#82b4e3", bg = "#f2edec" }
"constant.boolean"                = { fg = "#82b4e3", bg = "#f2edec" }
"constant.numeric"                = { fg = "#82b4e3", bg = "#f2edec" }
"error"                           = { fg = "#ffffff", bg = "#dd698c" }
"function"                        = { fg = "#25b7b8" }
"identifier"                      = { fg = "#958ac5" }
"keyword"                         = { fg = "#90b8ea" }
"keyword.operator"                = { fg = "#da8fbd" }
"statement"                       = { fg = "#bcb2e8" }
"string"                          = { fg = "#534e5b" }
"type"                            = { fg = "#958ac5" }
"variable"                        = { fg = "#c29ba3" }
```
